services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: ikai-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    profiles:
      - frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        VITE_API_URL: /api
    container_name: ikai-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped
